### ISSUE TITLE
Proxy Example

### ISSUE THREAD

**Issue by sandywater** [levigross/grequests#10]
Can you please give me an example of how to set a proxy for use with grequests?

Thank you.

**Comment by levigross** [comment]
Thank you for asking. I have been meaning to create an example directory but in the meantime, please see the code below.


Using A Proxy
============

Environment Variables
=================

By default, the library uses the golang `net/http` library which supports proxies via environment variables. 

These are set within the shell e.g

```bash
export HTTP_PROXY="http://127.0.0.1:8080"
export HTTP_PROXY="https://127.0.0.1:8080"
```

Or when launching the program

```
$ HTTP_PROXY=http://127.0.0.1:8080 ./myprog
```

Using Request Options
==================

`RequestsOptions` also supports the ability to specify a proxy. The format is `protocol`:`*url.URL` please see the example below:

```go
proxyURL, err := url.Parse("http://127.0.0.1:8080") // Proxy URL
if err != nil {
	panic(err)
}

resp, err := grequests.Get("http://www.levigross.com/",
  &grequests.RequestOptions{Proxies: map[string]*url.URL{proxyURL.Scheme: proxyURL}})
```

**Comment by sandywater** [comment]
@levigross much thanks!! :+1:
