### ISSUE TITLE
RequestOptions UseCookieJar seems not in use

### ISSUE THREAD

**Issue by aolu11** [levigross/grequests#16]
It seems that RequestOptions UseCookieJar parameter is specified but not used.

func BuildHTTPClient always use a cookie jar

**Comment by levigross** [comment]
Hi @aolu11 

I don't understand what you are asking, can you please be more specific in your question? Right now, the library will use `http.Client` if you don't request any `http.Client` modifications.  

```go
func (ro RequestOptions) dontUseDefaultClient() bool {
	return ro.InsecureSkipVerify == true ||
		ro.DisableCompression == true ||
		len(ro.Proxies) != 0 ||
		ro.TLSHandshakeTimeout != 0 ||
		ro.DialTimeout != 0 ||
		ro.DialKeepAlive != 0 ||
		len(ro.Cookies) != 0 ||
		ro.UseCookieJar != false
}
```

Will return `true` if a new `http.Client` is needed

**Comment by aolu11** [comment]
@levigross 

I mean, when we specify some custom request options, `dontUseDefaultClient()` will return true, and we still do not need cookie, so we set the `UseCookieJar` to false

but BuildHTTPClient will always create a cookieJar and ignore the `UseCookieJar` option, like:

`cookieJar, _ := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})`

And

`return &http.Client {  
    jar: cookieJar
    //...
}`

Am i miss something?

**Comment by levigross** [comment]
No you are not missing anything. I have just pushed a fix for this. Enjoy!
