### ISSUE TITLE
proposal:use custom cookieJar implementation

### ISSUE THREAD

**Issue by defia** [levigross/grequests#18]
now grequest use the official implmentation of cookieJar (net/http/cookiejar)

I think this one lacks some functions, such as exporting/importing all cookies of a session.

But it's no way to use custom cookiejar at the moment.

maybe it's better to use our own cookiejar implementation to add some features, or allow user to override the default ones.

**Comment by levigross** [comment]
You now have the ability to pass in your own cookieJar
