### ISSUE TITLE
Large response getting cut off.

### ISSUE THREAD

**Issue by matsch01** [levigross/grequests#30]
[simple_server.zip](https://github.com/levigross/grequests/files/483097/simple_server.zip)
Reading the response of a GET request using .String() arbitrarily cuts off the full response when the response is quite large (+5MB). The issue appears to occur when reading the internal buffer from the response object; the full response string is not returned.

Using http.Get() works fine:

Attached is a standalone project that reproduces the issue. The attached project has a simple server that returns a hard coded json string: 

src/simple_server

There are also two clients:

src/grequests_client (reproduces the issue)
src/http_client (works fine)

The error occurs in grequests_client when trying to decode the json response:  'use of closed network connection'. But inspecting the json response using resp.String() or resp.Byte() shows that only part of the json response is returned.

**Comment by levigross** [comment]
@matsch01 thank you for submitting this bug report. To help better address this bug can you please let me know which OS and go version you were using when you encountered this issue

**Comment by matsch01** [comment]
I'm using Windows 7 and Go 1.7.

**Comment by levigross** [comment]
Thanks! I am looking at the issue (thanks for the sample code) and I can reproduce it

**Comment by levigross** [comment]
I have removed the finalizer (which was closing the response too early) and will be pushing the build as soon as my branch's tests run

**Comment by levigross** [comment]
Can you please checkout the latest source code and tell me if you continue to encounter this issue?

**Comment by matsch01** [comment]
Issue has been resolved. Thank you.
