### ISSUE TITLE
Do not overwrite client.CheckRedirect

### ISSUE THREAD

**Issue by ReSTARTR** [levigross/grequests#44]
grequests always set client.ChekcRedirect.

https://github.com/levigross/grequests/blob/0.9/utils.go#L55

But I want to use my client.CheckRedirect function in a test code.

```go
client := http.Client{
    CheckRedirect: function() error {
        return errors.New("cancel redirection")
    },
}
r, err := grequests.Get("http://example.com/redirect", &grequests.RequestOptions{
    HTTPClient: &client,
})
```

Please support this feature?

**Comment by levigross** [comment]
This has been fixed
