### ISSUE TITLE
how  post  a byte date ?

### ISSUE THREAD

**Issue by tbure** [levigross/grequests#61]
such  as  post  /api 
but  post  data  is       text  , not  key=value ,i  cannot  use response.Data beacuse this  is  map[string]interface{}.

**Comment by tbure** [comment]
such  as  post  data :
    line1   ......
    line 2 ......

not  is key=value

**Comment by levigross** [comment]
Try the MultipartMime uploader https://godoc.org/github.com/levigross/grequests#example-package--PostFileUpload

**Comment by Jolly23** [comment]
@levigross It doesn't works

**Comment by Jolly23** [comment]
@levigross RequestBody is ok.
```go
		RequestBody: strings.NewReader(`{"username":"xxx","password":"xxx"}`),
```
