### ISSUE TITLE
Query string not being constructed

### ISSUE THREAD

**Issue by sarandafl** [levigross/grequests#65]
When sending a `GET`, with `Data map[string]string` set in the `RequestOptions{}`, the documentation in the package states following:
````
	// Data is a map of key values that will eventually convert into the
	// query string of a GET request or the body of a POST request.
````
Using  `.Get()` on the `*Session` and specifying the options in `Data`, the `content-type` in the http header is set to `Content-Type:[application/x-www-form-urlencoded]`. This causes the request to be interpreted as a `POST`. Either the code needs to be changed, or the documentation updated to state that `Data` should be used for `POST`s and `QueryStruct` should be used for `GET`s.

**Comment by levigross** [comment]
Thank you for bringing this to my attention. I would use `Params:` for the query string and I will update the documentation shortly
