### ISSUE TITLE
http proxy setting does not work when try to access websites with https

### ISSUE THREAD

**Issue by guest6379** [levigross/grequests#71]
```go
        proxyURL, err := url.Parse("http://127.0.0.1:8080") // Proxy URL
	if err != nil {
		log.Panicln(err)
	}

	resp, err := grequests.Get("http://www.google.com",
		&grequests.RequestOptions{Proxies: map[string]*url.URL{proxyURL.Scheme: proxyURL}})

	if err != nil {
		log.Println(err)
	}

	if resp.Ok != true {
		log.Println("Request did not return OK")
	}

	log.Println(resp)
```

The code above will work as expected.

But, if you replace `http://www.google.com`  to `https://www.google.com`, it will not work, it access google directly without the proxy you set!

**Comment by levigross** [comment]
You need to set a proxy for both`HTTP` and `HTTPS`

**Comment by guest6379** [comment]
> You need to set a proxy for both`HTTP` and `HTTPS`

I hope so, but unfortunately, sometimes only http proxy will be provided.
In most cases, set a proxy for http and https are not necessary(especially, a proxy listening on the localhost) 

Thanks
